export const AUTO_INCREMENT = 'autoIncrement'
export const AUTO_DECREMENT = 'autoDecrement'
export const ADMIN_INFO = 'admin_info'
export const ADMIN_INFO_CLEAR = 'adminInfoClear'
export const ADMIN_LOGIN = 'adminLogin'
export const ADMIN_INFO_INIT = 'adminInfoInit'
